# Rank Corelation

In [16]:
x=list(map(int,input().split()))
y=list(map(int,input().split()))
ranksx=[]
ranksy=[]
rx=[]
ry=[]
xsort=sorted(x,reverse=True)
ysort=sorted(y,reverse=True)
def ran(sort,ranks):
  k=0
  c=0
  c1=0
  sum1=0
  while(k<len(sort)):
    if(sort.count(sort[k])!=1):
      a=sort.count(sort[k])  
      while(c<a):
        k=k+1
        sum1=sum1+k
        c=c+1
      while(c1<a):
        rank=sum1/a
        ranks.append(rank)
        c1 =c1+1
    else:
      k+=1
      ranks.append(k)
    c=0
    c1=0
    sum1=0
  return ranks
ranksx=ran(xsort,ranksx)
ranksy=ran(ysort,ranksy)
def ran1(ranks,sort,a):
  k=0
  r=[]
  while(k<len(ranks)):
    j=a[k]
    r.append(ranks[sort.index(j)])
    k+=1
  return r
rx=ran1(ranksx,xsort,x)
ry=ran1(ranksy,ysort,y)
print(x)
print(rx)
print(y)
print(ry)
di=[]
disqr=[]
n=len(x)
for i in range(0,n):
    di.append(rx[i]-ry[i])
    disqr.append(di[i]*di[i])
print(disqr)
sdisqr=sum(disqr)
print(sdisqr)
repetedx=[]
for i in x:
    if(x.count(i)>1 and i not in repetedx):
        repetedx.append(i)
countsx=[]
for i in repetedx:
    c=x.count(i)
    countsx.append(c)
sumcfx=0
for i in countsx:
    s=(i*i*i-i)/12
    sumcfx=sumcfx+s
repetedy=[]
for i in y:
    if(y.count(i)>1 and i not in repetedy):
        repetedy.append(i)
countsy=[]
for i in repetedy:
    c=y.count(i)
    countsy.append(c)
sumcfy=0
for i in countsy:
    s=(i*i*i-i)/12
    sumcfy=sumcfy+s
print(repetedx)
print(repetedy)
sdisqr=sdisqr+sumcfx+sumcfy
print(sdisqr)
s=1-((6*sdisqr)/(n*((n**2)-1)))
print("Spearmanns Rank Coefficient:",s)

68 64 75 50 64 80 75 40 55 64
62 58 68 45 81 60 68 48 50 70
[68, 64, 75, 50, 64, 80, 75, 40, 55, 64]
[4, 6.0, 2.5, 9, 6.0, 1, 2.5, 10, 8, 6.0]
[62, 58, 68, 45, 81, 60, 68, 48, 50, 70]
[5, 7, 3.5, 10, 1, 6, 3.5, 9, 8, 2]
[1, 1.0, 1.0, 1, 25.0, 25, 1.0, 1, 0, 16.0]
72.0
[64, 75]
[68]
75.0
Spearmanns Rank Coefficient: 0.5454545454545454


# ANOVA one way

In [13]:
import scipy as sci
from scipy.stats import f_oneway
treatments=[]
k=int(input())
for i in range(k):
    l=list(map(int,input().split()))
    treatments.append(l)
los=float(input())
G=0
for i in treatments:
    G=G+sum(i)
n=0
for i in treatments:
    n=n+len(i)
rss=0
for i in treatments:
    for j in i:
        rss=rss+j*j
cf=G*G/length
sst=rss-cf
sums=[]
for i in treatments:
    a=sum(i)
    sums.append(a)
stn=[]
for i in range(0,len(sums)):
    b=(sums[i]*sums[i])/len(treatments[i])
    stn.append(b)
ssn=sum(stn)
sst=rss-cf
print(sst)
sstr=ssn-cf
print(sstr)
sse=sst-sstr
print(sse)
x=sstr/(k-1)
y=sse/(n-k)
F=x/y
print(F)
val=f.ppf(1-los,k-1,n-k)
print(val)
if(F>val):
    print("Reject H0")
else:
    print("Accept H0")

3
13 10 8 11 8
13 11 14 14
4 1 3 4 2 4
0.05
302.0
270.0
32.0
50.625
3.8852938346523933
Reject H0


# ANOVA two way

In [6]:
import scipy as sci
from scipy.stats import f_oneway
from scipy.stats import f
treatments=[]
blocks=[]
n=int(input())
for i in range(n):
    t=list(map(int,input().split()))
    treatments.append(t)
k=len(treatments[0])
i=0
while(i<k):
    b=[]
    for j in treatments:
        b.append(j[i])
    blocks.append(b)
    i=i+1
print(blocks)
sum1=0
for i in treatments:
    for j in i:
        sum1=sum1+j*j
rss=sum1
print(rss)
sum2=0
for i in treatments:
    sum2=sum2+sum(i)
g=sum2
cf=(g*g)/(k*n)
t1sqr=[]
for i in treatments:
    a=sum(i)*sum(i)
    t1sqr.append(a)
t1sq=sum(t1sqr)
bj=[]
for i in blocks:
    a=sum(i)
    bj.append(a)
bjsqr=[]
for i in bj:
    a=i*i
    bjsqr.append(a)
t1bj=sum(bjsqr)
sst=rss-cf
sstr=(1/k)*t1sq-cf
sstb=(1/n)*t1bj-cf
sse=sst-sstr-sstb
print(rss)
print(cf)
print(sst)
print(sstr)
print(sstb)
print(sse)
f1=n-1
f2=k-1
f3=f1*f2
tf=n*k-1
msst=sstr/f1
mssb=sstb/f2
msse=sse/f3
print(msst)
print(mssb)
print(msse)
ftrcal=msst/msse
fbcal=mssb/msse
print(ftrcal,fbcal)
ftabletr=f.ppf(1-0.05,f1,f3)
ftableb=f.ppf(1-0.05,f2,f3)
print(ftabletr,ftableb)
if(ftrcal>ftabletr):
    print("Treatments: Reject H0")
else:
    print("Treatments: Accept H0")
if(fbcal>ftableb):
    print("Blocks: Reject H0")
else:
     print("Blocks: Accept H0")

3
13 7 9 3
6 6 3 1 
11 5 15 5
[[13, 6, 11], [7, 6, 5], [9, 3, 15], [3, 1, 5]]
786
786
588.0
198.0
56.0
90.0
52.0
28.0
30.0
8.666666666666666
3.230769230769231 3.4615384615384617
5.143252849784718 4.757062663089414
Treatments: Accept H0
Blocks: Accept H0


# Multiple Linear Regression

In [28]:
import numpy as np

y=list(map(int,input("Enter Y data").split()))
y=np.transpose(y)
print(y)
Y=np.resize(y,(12,1))
print(Y.shape)
x1=[]
for i in range(0,len(y)):
    x1.append(1)
x2=list(map(int,input("Enter % of absenteeism").split()))
x3=list(map(int,input("Enter breakdown").split()))
X1=[]
X1.append(x1)
X1.append(x2)
X1.append(x3)
print("X:",X1)
X=np.transpose(X1)
print("X transpose:",X)
res=np.dot(X1,X)
print("Xtranxspose * X:",res)
res=np.linalg.inv(res)
print("(Xtranspose * X)inverse:",res)
res1=np.dot(X1,Y)
print("Xtranspose * Y:",res1)
B=np.dot(res,res1)
print("Beta:",B)
ycap=[]
for i in range(0,len(y)):
    y1=B[0]+(B[1]*x2[i])+(B[2]*x3[i])
    ycap.append(y1)
ycap=np.transpose(ycap)
print("ycap",ycap)
E=np.subtract(y,ycap)
print("Epslon:",E)
E1=np.transpose(E)
sse=np.dot(E,E1)
print("sse:",sse)
ymean=sum(y)/len(y)
print("Mean of y:",ymean)
sst=0
for i in range(0,len(y)):
    s=(y[i]-ymean)**2
    sst+=s
print("sst:",sst)
ssr=sst-sse
print("ssr:",ssr)
Rsqr=ssr/sst
print("R square:",Rsqr)
if(Rsqr<0.90):
    print("We reject the model")
else:
    print("We accept the model")

Enter Y data100 110 105 94 95 99 104 108 105 98 105 110
[100 110 105  94  95  99 104 108 105  98 105 110]
(12, 1)
Enter % of absenteeism9 8 7 14 12 10 7 4 6 5 7 6
Enter breakdown62 58 64 60 63 57 55 56 59 61 57 60
X: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [9, 8, 7, 14, 12, 10, 7, 4, 6, 5, 7, 6], [62, 58, 64, 60, 63, 57, 55, 56, 59, 61, 57, 60]]
X transpose: [[ 1  9 62]
 [ 1  8 58]
 [ 1  7 64]
 [ 1 14 60]
 [ 1 12 63]
 [ 1 10 57]
 [ 1  7 55]
 [ 1  4 56]
 [ 1  6 59]
 [ 1  5 61]
 [ 1  7 57]
 [ 1  6 60]]
Xtranxspose * X: [[   12    95   712]
 [   95   845  5663]
 [  712  5663 42334]]
(Xtranspose * X)inverse: [[ 4.08944026e+01  1.14046520e-01 -7.03043891e-01]
 [ 1.14046520e-01  1.17514524e-02 -3.49009300e-03]
 [-7.03043891e-01 -3.49009300e-03  1.23147269e-02]]
Xtranspose * Y: [[ 1233]
 [ 9636]
 [73094]]
Beta: [[133.46048243]
 [ -1.24850346]
 [ -0.35100837]]
ycap [[100.46143226 103.11396921 102.25642243  94.92093172  96.36491352
  100.96797067 105.41549778 108.80999978 105.25996775 105.806454

# Multivariate Linear Regression

In [2]:
import numpy as np
import scipy as sci
from scipy.stats import f_oneway
from scipy.stats import f
from scipy.stats import t
import math
k=int(input())
dependent=[]
for i in range(k):
    y=list(map(int,input().split()))
    dependent.append(y)
Yt=np.array(dependent)
l=len(y)
Y=np.transpose(Yt)
independent=[]
c=[]
for i in range(l):
    c.append(1)
independent.append(c)
n=int(input())
for i in range(n):
    x=list(map(float,input().split()))
    independent.append(x)
print(independent)
Xt=np.array(independent)
print(Xt)
X=np.transpose(Xt)
print(X)
t1=np.matmul(Xt,X)
tinv=np.linalg.inv(t1)
t2=np.matmul(Xt,Y)
bt=np.matmul(tinv,t2)
print(bt)
e=0
obs1=[]
obs2=[]
while(e<l):
    a=independent[0][e]
    b=independent[1][e]
    c=independent[2][e]
    d=independent[3][e]
    yval1=bt[0][0]*a+bt[1][0]*b+bt[2][0]*c+bt[3][0]*d
    yval2=y1=bt[0][1]*a+bt[1][1]*b+bt[2][1]*c+bt[3][1]*d
    obs1.append(yval1)
    obs2.append(yval2)
    e=e+1
print(obs1)
print(obs2)
error1=[]
error2=[]
for i in range(l):
    a=dependent[0][i]-obs1[i]
    error1.append(a)
    b=float(dependent[1][i]-obs2[i])
    error2.append(b)
print(error1)
print(error2)
sse1=0
sse2=0
for i in error1:
    sse1=sse1+i*i
for i in error2:
    sse2=sse2+i*i
ydep1=sum(dependent[0])/l
ydep2=sum(dependent[1])/l
sst1=0
sst2=0
for i in dependent[0]:
    diff=i-ydep1
    sst1=sst1+(diff*diff)
for i in dependent[1]:
    diff=i-ydep2
    sst2=sst2+(diff*diff)
ssr1=sst1-sse1
ssr2=sst2-sse2
r1=(ssr1/sst1)**1/2
r2=(ssr2/sst2)**1/2
if(r1>0.90):
    print('Accept Y1')
else:
    print('Reject Y1')
if(r2>0.90):
    print('Accept Y2')
else:
    print('Reject Y2')

2
10 12 11 9 9 10 11 12 11 10 11 12
100 110 105 94 95 99 104 108 105 98 103 110
3
9 8 7 14 12 10 7 4 6 5 7 6
62 58 64 60 63 57 55 56 59 61 57 60
1.0 1.3 1.2 0.8 0.8 0.9 1.0 1.2 1.1 1.0 1.2 1.2
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [9.0, 8.0, 7.0, 14.0, 12.0, 10.0, 7.0, 4.0, 6.0, 5.0, 7.0, 6.0], [62.0, 58.0, 64.0, 60.0, 63.0, 57.0, 55.0, 56.0, 59.0, 61.0, 57.0, 60.0], [1.0, 1.3, 1.2, 0.8, 0.8, 0.9, 1.0, 1.2, 1.1, 1.0, 1.2, 1.2]]
[[ 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1. ]
 [ 9.   8.   7.  14.  12.  10.   7.   4.   6.   5.   7.   6. ]
 [62.  58.  64.  60.  63.  57.  55.  56.  59.  61.  57.  60. ]
 [ 1.   1.3  1.2  0.8  0.8  0.9  1.   1.2  1.1  1.   1.2  1.2]]
[[ 1.   9.  62.   1. ]
 [ 1.   8.  58.   1.3]
 [ 1.   7.  64.   1.2]
 [ 1.  14.  60.   0.8]
 [ 1.  12.  63.   0.8]
 [ 1.  10.  57.   0.9]
 [ 1.   7.  55.   1. ]
 [ 1.   4.  56.   1.2]
 [ 1.   6.  59.   1.1]
 [ 1.   5.  61.   1. ]
 [ 1.   7.  57.   1.2]
 [ 1.   6.  60.   1.2]]
[[ 1.08969952e+01  9.10971989e+01]
 [

# MANOVA one way

In [1]:
from math import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import f
from scipy.stats import t
import scipy as sci

#------------------------------------------------------------------------------#
#Multi Variate regression..
#------------------------------------------------------------------------------#

t=[]
yi=[]
yb=[]
f=[]
c=0
s=0
u=0
p=[]
inputs=int(input("Enter no of treatments:"))
for i in range(inputs):
  l=[]
  ys=[]
  for j in range(2):
    r=list(map(int,input().split()))
    c+=len(r)
    k=sum(r)
    if j==0:u+=k
    else:s+=k
    ys.append(int(k/len(r)))
    l.append(r)
  yi.append(ys)
  t.append(l)
p.append(int(u/(c/2)))
p.append(int(s/(c/2)))
print("c=",c)
print("p=",p)
print("t=",t)
print("yi=",yi)
sse1=0
sst1=0
for i in range(len(t)):
  for j in range(len(t[i][0])):
    sse1+=(t[i][0][j]-yi[i][0])**2
    sst1+=(t[i][0][j]-p[0])**2
ssr1=sst1-sse1
print("sse1=",sse1)
print("sst1=",sst1)
print("ssr1=",ssr1)
sse2=0
sst2=0
ssr2=0
for i in range(len(t)):
  for j in range(len(t[i][1])):
    sse2+=(t[i][1][j]-yi[i][1])**2
    sst2+=(t[i][1][j]-p[1])**2
ssr2=sst2-sse2
print("sse2=",sse2)
print("sst2=",sst2)
print("ssr2=",ssr2)
sse12=0
sst12=0
ssr12=0
for i in range(len(t)):
  for j in range(len(t[i][0])):
    sse12+=((t[i][0][j]*t[i][1][j])-(yi[i][0]*yi[i][1]))
    sst12+=((t[i][0][j]*t[i][1][j])-(p[0]*p[1]))
ssr12=sst12-sse12
print("sse12=",sse12)
print("sst12=",sst12)
print("ssr12=",ssr12)

b=(ssr1*ssr2)-((ssr12)**2)
w=(sse1*sse2)-((sse12)**2)
ta=(sst1*sst2)-((sst12)**2)
lmd=w/ta
print("lambda=",lmd)
# one=(c-inputs-1)/(inputs-1)
# two=(1-(lmd**0.5))/(lmd**0.5)
# print(one,two)
f=(((c/2)-inputs-1)/(inputs-1))*((1-(lmd**0.5))/(lmd**0.5))
print("F-value is:",f)

Enter no of treatments:3
2 3 5 2
3 4 4 5
4 5 6
8 6 7
7 8 10 9 7
6 7 8 5 6
c= 24
p= [5, 5]
t= [[[2, 3, 5, 2], [3, 4, 4, 5]], [[4, 5, 6], [8, 6, 7]], [[7, 8, 10, 9, 7], [6, 7, 8, 5, 6]]]
yi= [[3, 4], [5, 7], [8, 6]]
sse1= 15
sst1= 82
ssr1= 67
sse2= 10
sst2= 35
ssr2= 25
sse12= 24
sst12= 117
ssr12= 93
lambda= 0.03937517330622054
F-value is: 16.15806086508262


#  Fischer Linear Discriminant Analysis

In [2]:
import numpy as np
import scipy.stats as ss
a = int(input('number of input variables:'))
X = []

for i in range(a):
    l = list(map(float,input(f'input for row {i+1} : ').split()))
    X.append(l)

one = []
for i in range(len(X[0])):
    one.append(1)
X.append(one)

Y = list(input('Output Variable: ').split())
for i in range(len(Y)):
    if Y[i].capitalize() == 'Yes':
        Y[i] = 1
    elif Y[i].capitalize() == 'No':
        Y[i] = 0
    else:
        print('Invalid input!')

print(X)
print(Y)
X[1],X[0],X[-1] = X[0] ,X[-1],X[1]
print(X)
XN = np.array(X).transpose()
print(XN)
Xt = XN.transpose()
B = np.matmul((np.linalg.inv(np.matmul(Xt,XN))),np.matmul(Xt,Y))

for i in range(len(B)):
    B[i] = round(B[i],4)
print(B)
ex = list(map(float,input('Enter the Observation to be Evaluated : ').split()))

ans = (B[0]+(B[1]*ex[0])+(B[2]*ex[1]))
an = round(ans)
print('Yes' if an == 1 else 'No')

number of input variables:2
input for row 1 : 2.95 2.53 3.57 3.16 2.58 2.16 3.27
input for row 2 : 6.63 7.79 5.65 5.47 4.46 6.22 3.52
Output Variable: Yes Yes Yes Yes No No No
[[2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27], [6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52], [1, 1, 1, 1, 1, 1, 1]]
[1, 1, 1, 1, 0, 0, 0]
[[1, 1, 1, 1, 1, 1, 1], [2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27], [6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52]]
[[1, 1, 1, 1, 1, 1, 1], [2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27], [6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52]]
[[1.   2.95 6.63]
 [1.   2.53 7.79]
 [1.   3.57 5.65]
 [1.   3.16 5.47]
 [1.   2.58 4.46]
 [1.   2.16 6.22]
 [1.   3.27 3.52]]
[-3.9116  0.8533  0.3555]
Enter the Observation to be Evaluated : 2.81 5.46
No


# Linear Discriminant Analysis

In [2]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import f
from scipy.stats import t
import scipy as sci

#------------------------------------------------------------------------------#
#Fischer's Linear Discriminant Analysis fit...

#Test cases
# 1300 1260 1220 1180 1060 1140 1100 1020 980 940
# 2.7 3.7 2.9 2.5 3.9 2.1 3.5 3.3 2.3 3.1
# 1 1 1 1 1 0 0 0 0 0

sat=float(input("Enter sat value:"))
gpa=float(input("Enter gpa value:"))
print("Enter independent variables:")
t=list(map(int,input().split()))
l=[]
l.append([1 for i in range(len(t))])
n=int(input("Enter no.of Dependent Variables:"))
for i in range(n):
  temp=list(map(float,input().split()))
  l.append(temp)

xt=np.array(l)
x=np.transpose(xt)
t=np.array(t)
print(l)
b=np.matmul(np.linalg.inv((np.matmul(xt,x))),(np.matmul(xt,t)))
print(b)
y=b[0]+(b[1]*sat)+(b[2]*gpa)
print(y)

Enter sat value:1000
Enter gpa value:2.9
Enter independent variables:
1 1 1 1 1 0 0 0 0 0
Enter no.of Dependent Variables:2
1300 1260 1220 1180 1060 1140 1100 1020 980 940
2.7 3.7 2.9 2.5 3.9 2.1 3.5 3.3 2.3 3.1
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1300.0, 1260.0, 1220.0, 1180.0, 1060.0, 1140.0, 1100.0, 1020.0, 980.0, 940.0], [2.7, 3.7, 2.9, 2.5, 3.9, 2.1, 3.5, 3.3, 2.3, 3.1]]
[-3.83919635e+00  3.23263173e-03  2.39549603e-01]
0.0881292316750063
